### ISSUE TITLE
insta flight (goto upgrades...this ones old)

### ISSUE THREAD

**Issue by zach2639** [DarkholmeTenk/TardisModIssues#186] opened 2015-06-01 14:06 UTC
you should add a module that allows faster travel on long flights...like in the show

**Comment by FoxPotato** [comment] 2015-06-01 14:49
could you be a bit more specific.

**Comment by Soyaro666** [comment] 2015-06-01 14:59
he wants a way to get even more speed while flying. maybe quicksilver like I suggested in #185 ? Or had you something else in mind, @epicnesslol ?

**Comment by DarkholmeTenk** [comment] 2015-06-01 15:05
Speed is planned to be added to the list of things points can be spent on.

**Comment by zach2639** [comment] 2015-06-01 15:22
i had a upgrade module in mind... and a few module holders were you can put modles you found in dundeons (the pannel is were the upgrade gaghes are) and its either a upgradeable thing or a toggleswitch (the one i talk about above is a toggle for instant flight, like in the show)

**Comment by Soyaro666** [comment] 2015-06-01 15:30
so you want to completely remove the actual flight and just start and land, no matter how far the distance is?
since the tardis is a time machine it could actually do that but wouldn't it be a little overpowered? It already is a real fast way to travel huge distances.
I don't like the idea of completely removing the flight. of course that's just my opinion... at least it could come with a config option to disable this feature ^^

**Comment by zach2639** [comment] 2015-06-01 15:32
to open the panel set a sonic device to reconfigure to take off the panel, there is 4 pannels (upgradeable) were you can fit upgrades,once a upgrade is fitted its either a switch or a meter (toggleswithes cost 1 upgrade to unlock, then you can switch it at ease) 
(removal of a upgrade is hard...no quick ideas for this one...)

**Comment by FoxPotato** [comment] 2015-06-01 15:33
Is your suggestion a way to travel faster or to have upgrades. Maybe make another post for that, seeing as the way for faster travel will be done by spending points.

**Comment by zach2639** [comment] 2015-06-01 15:34
and Soyaro666, its a very rare  upgrade in dundeaons Then you need to ullock it with a point,but still cofig is just if you dont like something soooo good idea

**Comment by zach2639** [comment] 2015-06-01 15:35
and foxpatato...i guss you right but, they would have to be linked somehow...you got any ideas as insta flight is a upgrade

**Comment by Soyaro666** [comment] 2015-06-01 15:53
make a post for your upgrade system and put a list of possible upgrades in that post. that would be less confusing than this post ;-)

**Comment by zach2639** [comment] 2015-06-01 16:06
good idea

------------------------POST CLOSED---------------

**Comment by zach2639** [comment] 2015-06-01 17:23
https://github.com/DarkholmeTenk/TardisModIssues/issues/187 is were the new one is :)

**Comment by DarkholmeTenk** [comment] 2015-06-02 16:25
Duplicate of #187

**Closed as completed by DarkholmeTenk** 2015-06-02 16:25 UTC

**Comment by zach2639** [comment] 2015-06-02 16:55
its more organised...and a little extra

**Comment by Soyaro666** [comment] 2015-06-02 16:58
and he want's to keep his issues tracker organized I guess. doesn't matter, because of the two (now three) mentions of #187 everybody who reads that will know this one exists. and for him it's easier to see what's waiting for his attention

**Comment by zach2639** [comment] 2015-06-02 18:35
is ANYONE going to post something on the new post...this one filled up in a minute...the new one has dustbunnys floating around
