### ISSUE TITLE
[ENHANCE] Doors, Regeneration, Eye of Harmony & Bug

### ISSUE THREAD

**Issue by ghost** [DarkholmeTenk/TardisModIssues#391] opened 2016-01-05 08:29 UTC
Hello! I have some suggestion.
I think you can make it open. I mean you can make doors open and display texture inside TARDIS model, just make a new shape inside TARDIS model box and display interior texture based on interion number or something like this.
Also, inside TARDIS you can make doors as model too and display inside diffrend textures. Or if you in Time Vortex you can simply open doors and see the Vortex texture. This shouldn's be too hard realy.

Another suggestion
REGENERATION! Not only Doctor regenerates! This isn't too hard, but VERY needed! I know, there is regeneration in Dalek mod, but about that later. I think mod REALY needs this. While you travelling, you player takes some Artron energy (Write to NBT, nothing hard) and when he got A LOTS of energy (and make a command) he got 1 regeneration. Yep, don't change face. But make it better and LONGER than in Dalek mod.

Eye of Harmony. I'm very sorry if somebody else created this enchancement, but this is VERY important part of TARDIS! Such important! Realy! And it can be damaged while TARDIS got damage.
Also, i think you must add more effects while damaging, such as big explosions, real hull damaging, etc.

Now, bug: TARDIS dimensions conflicts with Dalek mod dimensions. But it's rather Dalek mod bug: i can't make TARDIS even if i change dimension in Dalek mod config. I think you should add config feature tu change TARDIS dimensions. I mean, start dimension. Not 2, 3, 4...

**Comment by FoxPotato** [comment] 2016-01-05 08:34
Regeneration won't get added, this is a TARDIS mod. Regeneration is more doctor who based. Also, idk if this is still gonna happen, but dark will in the future add looking glass api support. So you can look into the TARDIS in real time. and ofc, outside of it.
And I don't think it's that safe to open the doors during flight.

**Comment by ghost** [comment] 2016-01-05 08:39
And sorry for my bad english and twice changed name. My computer lags...

**Comment by ghost** [comment] 2016-01-05 08:42
Yes, but then i think he should add function to disable it due to lags. Or make it work without lags, but idk how it can work without lags.

**Comment by FoxPotato** [comment] 2016-01-05 08:43
I think there should be an option in general to turn it on/off.
But i haven't heard anything about it lately, so idk if it's still on the agenda or not.

**Comment by ghost** [comment] 2016-01-05 08:45
Actualy i don't think that it will be a good addition, it is boring. Better to exit from the TARDIS and get in lava XD

**Comment by DarkholmeTenk** [comment] 2016-01-05 18:48
Opening and closing doors isn't going to happen any time soon because it would require a large rework of the chameleon circuit system and I'd have to do a lot more modelling.

Regeneration is a no, because it'd be a pain to implement and as Fox said, this is a TARDIS mod, not a Dr Who mod.

Eye of harmony is a duplicate of #152 #141 

The bug is not a bug, the prospercraft drtardis pack works with both dalek mod and tardis mod. Tardis mod always checks if a dimension is already registered when the dimension is created.
I'm not adding a config to change the start dimension, because I'm just using "DimensionManager.getNextFreeDimId();" which is a forge function.
If it isn't working for you, create a new issue about just this bug, include some more details like console output, when you try to create it, etc.

Please separate things out in future, because it makes it much easier to keep track of what's been dealt with and keeps discussion more streamlined :)

**Closed as completed by DarkholmeTenk** 2016-01-05 18:48 UTC
