### ISSUE TITLE
[ENHANCE] recoloring rooms easier

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#122] opened 2015-05-17 00:57 UTC
after I demonstrated the Tardis mod to my girlfriend she gave me a request. she wished a red interior. well, the kind of wish a girl uses to say "why isn't it done yet?"
while i've been recoloring the control room i realized: it's terribly much work since you have to recolor every single block. so I thought about how to make it easier:

could one just press sneak while rightclicking to recolor all connected blocks of that type? connected by block type and color, if thats possible. so one could say "that wall is supposed to be red" and at a most of 3 clicks it is red. at least it could help handling another problem: the roof is too high, in survival I'd have to build a kind of scaffold to reach it on the uppest two to three layers (I can reach the third layer when I'm jumping. thats even more annoying than recoloring the floor in whole)

**Comment by DarkholmeTenk** [comment] 2015-05-17 00:58
Duplicate of #42

**Closed by DarkholmeTenk** 2015-05-17 00:58 UTC
Labels: duplicate

**Comment by Soyaro666** [comment] 2015-05-17 00:59
ah, sorry. didn't see that
