### ISSUE TITLE
Tardis Applied Energistics

### ISSUE THREAD

**Issue by dillasyx** [DarkholmeTenk/TardisModIssues#570] opened 2016-10-30 14:43 UTC
I have to restart the world, that new ME Devices connect to ME System and on every restart I have to replace the core, that the system generally starts working via roundels
Also when I directly place the ME Controller on more than one Roundel, only one will be used with 32 channels.
And cables have to be replaced to connect to the roundel again
Even if there isn't a direct connection and i connect 16 dense cables with different colors, only 32 channels will connect only through one cable, the other won't be used
is it possbile for each roundel 32 channels or limitless, so only the cables make a limit?
Even when channels are disabled in config, the tardis won't handle more than 2 quantum bridges and break the whole me system if more are connected.

**Comment by AlienXtream** [comment] 2016-10-30 23:07
if you have a security terminal on your ME network then the tardis doesn't actually have permission to modify it. its a weird quirk of how AE2 works. add a blank biometric card to the security terminal with permission to "modify network"

**Comment by AlienXtream** [comment] 2016-10-30 23:10
put a blank biometric card in your security station. 32 channel limit is hard coded in the AE2 API. the AE2 devs would need to add in a function on their end for limitless network relaying. alternatively you can use P2P tunnels or disable AE2's channels entirely via the configs

**Comment by dillasyx** [comment] 2016-10-30 23:14
i disabled channels completly, everything works now, thanks

**Comment by dillasyx** [comment] 2016-11-02 14:15
I disabled channels and put a biometric card into the ME System, so every user has all rights, just to test everything. I recognized some strange things with the time. I changed the roundel RF/tick up to around 80kRF/t to be sure, energy isn't the issue. Then i built a system with autocrafting and so on. First "bug" when i build more than 2 quantum bridges the whole system crashes. When I send a crafting request the system crashes. So I wanted to find the bug and built everything without roundels. Just placed cables through the tardis and disconnected all roundels. The System uses around 1k-2k RF/t and works correctly with just cables. I don't know a possible reason, do you have an idea? Should i try latest jenkins build or wait for a new release?
EDIT: newest jenkins build also doesn't work. 2+ quantum bridges are too much and more than one molecular assembler too

**Comment by AlienXtream** [comment] 2016-11-03 05:05
odd... ive not run into issues such as that and i was testing the ME system integration for dark while he was implementing the linking system. if you could do the following. 

1)recreate a system that causes the problem so that it can fit in a single screen shot
2)provide the version number of AE2 and AE2 addons you are using with config settings

put that info here and i will look into it on my instance to try and track down the culprit

**Comment by dillasyx** [comment] 2016-11-03 15:56
AE2 -              rv2-stable-10
AE2 Stuff -      0.5.0.56-mc1.7.10
ExtraCells2 -   1.7.10-2.3.14b197

any system that is using more than 2k RF/t breaks

![2016-11-03_16 51 19](https://cloud.githubusercontent.com/assets/11612223/19973717/4e6b4aea-a1e6-11e6-91d5-8a73319fdaf3.png)

**Comment by AlienXtream** [comment] 2016-11-03 20:36
O.o im on rv3. dose the ME system die only when connected to the tardis or does it die when setup "normally" as well?

**Comment by dillasyx** [comment] 2016-11-03 20:41
only on tardis

**Comment by AlienXtream** [comment] 2016-11-03 20:42
well im fighting a tps issue atm but once that calms down im going to (try to) bump up my ME systems power requirements

**Comment by dillasyx** [comment] 2016-11-03 20:59
okay, all i find out is doesn't matter what is connected, the tardis me system just allows energy input of 2k RF/t, then system shuts down due to energy loss. I you're around 1.9k RF/t and store Stacks of items the terminal shuts down after every stack, then reboots. More energy acceptor have no effect to the system. Easy to test with the Wireless Transmitter and 64 range upgrades because it needs 8k RF/t and instantly shut down everything.

**Comment by AlienXtream** [comment] 2016-11-03 21:06
and i just vein mined my AE setup....

**Comment by AlienXtream** [comment] 2016-11-03 21:22
im having no issues

**Comment by dillasyx** [comment] 2016-11-03 21:26
which version are you using? newest beta? and whats your rf/t?

**Comment by AlienXtream** [comment] 2016-11-03 21:27
rv_beta_5 over 8k. what ever the issue is thats causing your problem appears to either be AE2 stuff (incompatible with rv3 iirc) or an older bug that was fixed in later AE2 versions

**Comment by dillasyx** [comment] 2016-11-03 21:34
ae2 stuff is such usefull, but if it works only without it, i have to remove it, I'm trying now

**Comment by AlienXtream** [comment] 2016-11-03 21:35
i know its useful but like i said, it may just be cos you are using an older version of AE2.

**Comment by dillasyx** [comment] 2016-11-03 21:37
i tried with beta 6, but still same, the energy cell just gives 2k RF/t, now i try without aestuff

**Comment by AlienXtream** [comment] 2016-11-03 21:38
also, are you giving it enough rf/t? i assume you are but i never did ask

**Comment by dillasyx** [comment] 2016-11-03 21:40
i use the creative energy cell so it should, i guess, wait i have a look, because it still dont work

**Comment by AlienXtream** [comment] 2016-11-03 21:41
the creative EC has a configured max output

**Comment by AlienXtream** [comment] 2016-11-03 21:42
and if it helps om feeding power straight into the MEcontroler

**Comment by dillasyx** [comment] 2016-11-03 21:43
output is at 500k RF/t, should be enough and without channels there is no MEcontroller

**Comment by AlienXtream** [comment] 2016-11-03 21:44
have you tried adding ME energy cells (normal, not creative)

**Comment by AlienXtream** [comment] 2016-11-03 21:45
beyond that im stumped

**Comment by dillasyx** [comment] 2016-11-03 21:46
wow, now it works, i always used the energy acceptor, but 
okay now i feel stupid

**Comment by AlienXtream** [comment] 2016-11-03 21:47
me controler work?

**Comment by dillasyx** [comment] 2016-11-03 21:48
no controller ingame after channel deactivated, it's not needed but system works now
thank you

**Comment by AlienXtream** [comment] 2016-11-03 21:49
ok. your issue was obviously the me energy acceptor does not have a big enough internal buffer for more than 2k rf

**Comment by dillasyx** [comment] 2016-11-03 21:50
yeah but when i place a acceptor on the energy cell and then the creative cell there are around 2.3k Rf/t through the acceptor, it's weird

**Comment by dillasyx** [comment] 2016-11-03 21:51
but anyway it works, thank you a lot for your time

**Comment by AlienXtream** [comment] 2016-11-03 21:51
np :P

**Comment by AlienXtream** [comment] 2016-11-05 15:45
care to close this issue @nidico100

**Closed as completed** 2016-11-05 16:03 UTC
