### ISSUE TITLE
[Crash] Tardis Mod Crashes Server

### ISSUE THREAD

**Issue by Wxam** [DarkholmeTenk/TardisModIssues#540] opened 2016-06-25 20:17 UTC
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 6/25/16 9:23 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: io.darkcraft.darkcore.mod.network.PacketHandler.registerHandler(ILio/darkcraft/darkcore/mod/interfaces/IDataPacketHandler;)Z
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchMethodError: io.darkcraft.darkcore.mod.network.PacketHandler.registerHandler(ILio/darkcraft/darkcore/mod/interfaces/IDataPacketHandler;)Z
    at tardis.common.network.TardisPacketHandler.registerHandlers(TardisPacketHandler.java:23)
    at tardis.TardisMod.doingInit(TardisMod.java:219)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    ... 5 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.13.0-74-generic
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 3120599296 bytes (2976 MB) / 4122476544 bytes (3931 MB) up to 4122476544 bytes (3931 MB)
    JVM Flags: 3 total; -Xmx4096M -Xms4096M -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 119 mods loaded, 119 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](custom.jar) 
    UCHI    Forge{10.13.4.1614} [Minecraft Forge](custom.jar) 
    UCHI    appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core](minecraft.jar) 
    UCHI    Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHI    ivtoolkit{1.2.1} [IvToolkit](minecraft.jar) 
    UCHI    NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHI    RenderPlayerAPI{1.4} [Render Player API](minecraft.jar) 
    UCHI    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHI    debug{1.0} [debug](denseores-1.6.2.jar) 
    UCHI    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHI    StartingInventory{1.7.10.r03} [StartingInventory]([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
    UCHI    CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHI    advancedgenetics{1.5.9} [Advanced Genetics](advancedgenetics-1.7.10-1.5.9.jar) 
    UCHI    AgriCraft{1.7.10-1.5.0} [AgriCraft](AgriCraft-1.7.10-1.5.0.jar) 
    UCHI    appliedenergistics2{rv3-beta-6} [Applied Energistics 2](appliedenergistics2-rv3-beta-6.jar) 
    UCHI    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHI    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHI    Railcraft{9.12.2.0} [Railcraft](Railcraft_1.7.10-9.12.2.0.jar) 
    UCHI    ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    chisel{2.9.5.11} [Chisel](Chisel-2.9.5.11.jar) 
    UCHI    koresample{1.7.10-1.3.2} [Kore Sample](KoreSample-1.7.10-1.3.2.jar) 
    UCHI    StorageDrawers{1.7.10-1.9.9} [Storage Drawers](StorageDrawers-1.7.10-1.9.9.jar) 
    UCHI    dendrology{1.7.10-1.6.4} [Ancient Trees](AncientTrees-1.7.10-1.6.4.jar) 
    UCHI    AntMan{Beta-1.7.10-1.5.4} [AntMan](AntMan-Beta-1.7.10-1.5.4.jar) 
    UCHI    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) 
    UCHI    ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.4-114.jar) 
    UCHI    ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHI    ImmersiveEngineering{0.7.7} [Immersive Engineering](ImmersiveEngineering-0.7.7.jar) 
    UCHI    Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHI    ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCHI    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHI    TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHI    Armory{1.1.0.1-260} [Armory](Armory-1.1.0.1-260.jar) 
    UCHI    Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHI    Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
    UCHI    AromaBackup{0.1.0.0} [AromaBackup](AromaBackup-1.7.10-0.1.0.0.jar) 
    UCHI    AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.7.10-0.1.0.0.jar) 
    UCHI    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
    UCHI    BetterFoliage{2.0.9} [Better Foliage](BetterFoliage-MC1.7.10-2.0.9.jar) 
    UCHI    BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar) 
    UCHI    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UCHI    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar) 
    UCHI    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) 
    UCHI    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) 
    UCHI    BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCHI    Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
    UCHI    BrandonsCore{1.0.0.12} [Brandon's Core](BrandonsCore-1.0.0.12.jar) 
    UCHI    CarpentersBlocks{3.3.8} [Carpenter's Blocks](Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
    UCHI    cfm{3.4.8} [�9MrCrayfish's Furniture Mod](cfm-3.4.8-mc1.7.10.jar) 
    UCHI    ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHI    CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) 
    UCHI    darkcore{0.41} [Dark Core](darkcore-0.41-179.jar) 
    UCHI    DraconicEvolution{1.0.2g} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.2g.jar) 
    UCHI    endercore{1.7.10-0.2.0.36_beta} [EnderCore](EnderCore-1.7.10-0.2.0.36_beta.jar) 
    UCHI    EnderIO{1.7.10-2.3.0.427_beta} [Ender IO](EnderIO-1.7.10-2.3.0.427_beta.jar) 
    UCHI    EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCHI    EnderTech{1.7.10-0.3.2.405} [EnderTech](EnderTech-1.7.10-0.3.2.405.jar) 
    UCHI    enhancedportals{3.0.12} [EnhancedPortals](EnhancedPortals_1.7.10-universal-3.0.12.jar) 
    UCHI    enviromine{1.3.124} [EnviroMine](EnviroMine-1.3.124.jar) 
    UCHI    extrabuttons{1.7.10.1} [ExtraButtons](ExtraButtons-1.7.10.1.jar) 
    UCHI    extracells{2.3.14} [Extra Cells 2](ExtraCells-1.7.10-2.3.14b197.jar) 
    UCHI    ExtraTiC{1.4.6} [ExtraTiC](ExtraTiC-1.7.10-1.4.6.jar) 
    UCHI    farseek{1.0.11} [Farseek](Farseek-1.0.11.jar) 
    UCHI    HardcoreDarkness{1.7} [Hardcore Darkness](HardcoreDarkness-MC1.7.10-1.7.jar) 
    UCHI    HelpFixer{1.0.7} [HelpFixer](HelpFixer-1.0.7.jar) 
    UCHI    immersiveintegration{0.6.8} [Immersive Integration](immersiveintegration-0.6.8.jar) 
    UCHI    infiniteinvo{1.0.52} [InfiniteInvo](InfiniteInvo-1.0.52.jar) 
    UCHI    IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHI    journeymap{5.1.4p1} [JourneyMap](journeymap-1.7.10-5.1.4p1-unlimited.jar) 
    UCHI    k4lib{1.7.10-0.1.57} [K4Lib](k4lib-1.7.10-0.1.57-universal.jar) 
    UCHI    Login_Shield{1.2-9-g9bd1b47} [Login Shield](Login_Shield-1.2-9-g9bd1b47.jar) 
    UCHI    LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
    UCHI    malisiscore{1.7.10-0.14.3} [MalisisCore](malisiscore-1.7.10-0.14.3.jar) 
    UCHI    malisisdoors{1.7.10-1.13.2} [Malisis' Doors](malisisdoors-1.7.10-1.13.2.jar) 
    UCHI    Mekanism{9.0.2} [Mekanism](Mekanism-1.7.10-9.0.2.271 %281%29.jar) 
    UCHI    MekanismGenerators{9.0.2} [MekanismGenerators](MekanismGenerators-1.7.10-9.0.2.271 %281%29.jar) 
    UCHI    MekanismTools{9.0.2} [MekanismTools](MekanismTools-1.7.10-9.0.2.271 %281%29.jar) 
    UCHI    MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHI    Morpheus{1.7.10-1.6.21} [Morpheus](Morpheus-1.7.10-1.6.21.jar) 
    UCHI    NetherOres{1.7.10R2.3.1} [Nether Ores](NetherOres-[1.7.10]2.3.1-22.jar) 
    UCHI    netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.7.10-1.1.0.jar) 
    UCHI    ProjectE{1.7.10-PE1.10.0} [ProjectE](ProjectE-1.7.10-PE1.10.0.jar) 
    UCHI    MrTJPCoreMod{1.1.0.33} [MrTJPCore](MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
    UCHI    ProjRed|Core{4.7.0pre12.95} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
    UCHI    ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHI    ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHI    ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
    UCHI    ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
    UCHI    ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHI    ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
    UCHI    ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
    UCHI    ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHI    RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCHI    corerm{1.0c} [RikMuld's Core](RikMuldsCore_1.0c %281%29.jar) 
    UCHI    SIV{1.7.10-1.0.4} [ServerInfoViewer](ServerInfoViewer-1.7.10-1.0.4-universal.jar) 
    UCHI    streams{0.2} [Streams](Streams-0.2.jar) 
    UCHE    TardisMod{0.994} [Tardis Mod](tardismod-1.7.10-0.994-124-DS.jar) 
    UCHI    camping{2.1g} [The Camping Mod 2](TheCampingMod_2.1g.jar) 
    UCHI    ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.2.0-171.jar) 
    UCHI    TMechworks{0.2.15.106} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.15.106.jar) 
    UCHI    Translocator{1.1.2.16} [Translocator](Translocator-1.7.10-1.1.2.16-universal.jar) 
    UCHI    VeinMiner{0.33.0_1.7.10-986afb0} [Vein Miner](VeinMiner-0.33.0-1.7.10r466+986afb0.jar) 
    UCHI    VeinMinerModSupport{0.33.0_1.7.10-986afb0} [Mod Support](VeinMiner-0.33.0-1.7.10r466+986afb0.jar) 
    UCHI    WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.6.jar) 
    UCHI    wawla{1.3.1} [What Are We Looking At](Wawla-1.0.5.120.jar) 
    UCHI    ae2wct{1.7.10-rv3-1.8.7.1b} [AE2 Wireless Crafting Terminal](WirelessCraftingTerminal-1.7.10-rv3-1.8.7.1b.jar) 
    UCHI    witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCHI    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    yegamolchattels{1.1.2} [Ye Gamol Chattels](YeGamolChattels-1.1.2.jar) 
    UCHI    McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHI    MCFrames{1.0} [MCFrames](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHI    RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UCHI    denseores{1.0} [Dense Ores](denseores-1.6.2.jar) 
    UCHI    ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    CoFHCore: -[1.7.10]3.1.2-325
    AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
    ThermalFoundation: -[1.7.10]1.2.4-114
    Mantle Environment: Environment healthy.
    ThermalExpansion: -[1.7.10]4.1.2-240
    TConstruct Environment: Environment healthy.
    NetherOres: -[1.7.10]2.3.1-22
    ThermalDynamics: -[1.7.10]1.2.0-171
    Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
    EnderIO: Found the following problem(s) with your installation:
                  \* The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.1.0 from CoFHCore-[1.7.10]3.1.2-325.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

---

If anyone can help me fix this problem, i would appreciate that

**Comment by TheTrueForce** [comment] 2016-06-25 22:20
This looks to me like a duplicate of my one: #537. I switched to the latest alpha version, and it's worked so far.

Also, attach the fml-client-latest.log file or upload it to pastebin next time. And don't use the crash log file; the log has the crash log and also extra info that is quite helpful in debugging.

**Comment by DarkholmeTenk** [comment] 2017-04-02 14:26
This is related to using incompatible versions of TM and DC

**Closed as completed by DarkholmeTenk** 2017-04-02 14:26 UTC
