### ISSUE TITLE
[BUG] Temporal Dirt Causes Right Click to Stop working while in Tardis dimension

### ISSUE THREAD

**Issue by ndbarber** [DarkholmeTenk/TardisModIssues#195] opened 2015-06-03 22:36 UTC
Behavior:
Given I have created temporal dirt
And I put seeds on it
When the temporal dirt causes the seeds to grow
And I harvest them
Then some indeterminate time after that I can no longer use "right-click" functions like switching my screwdriver mode or reading a Thaumonomicon.

Workaround: 
I have found that if I switch from day to night with the temporal control button on the tardis console, I can use my right-click again.

**Comment by DarkholmeTenk** [comment] 2015-06-04 04:53
You have hunger overhaul installed, I imagine.
99% certain this is a bug caused by hunger overhaul using an access transformer to modify the right click function of generic items and you'd get the same effect if you used regular farmland instead of temporal dirt.

**Comment by ndbarber** [comment] 2015-06-04 18:01
Hey thanks for the reply!

I do not get the same effect with normal farmland.

I'll disable all my mods but darkcore and tardis and attempt to reproduce
the issue as a sanity check. If I fail to reproduce with only the tardis
mod, then I'll add hunger overhaul and try again.

**Comment by ndbarber** [comment] 2015-06-07 12:59
Yeah the bug only happens when I add hunger overhaul. I don't get the same effect using normal farmland and bone meal. Eventually (not sure how long, it was broken for days on our server) it's like the game "catches up" and the right-click stuff is functional again. The only other way to workaround that I've found is to hit the day/night switch so you can actually dismantle the temporal dirt.

**Comment by DarkholmeTenk** [comment] 2015-06-07 15:10
Do you get the bug with normal farmland if it's in a TARDIS though?

**Comment by ndbarber** [comment] 2015-06-07 19:34
Nope I have a successful farm inside the tardis of normal farmland.

**Comment by DarkholmeTenk** [comment] 2015-06-07 20:43
That's really weird, the last time I saw the bug it affected normal farmland :P
Either way, I think this is a bug which I can't fix; Hunger Overhaul's doing some weird stuff; I've messaged the author of hunger overhaul and I'm going to close this for now, since I think it's a problem in hunger overhaul more than TARDIS mod.

**Comment by ndbarber** [comment] 2015-06-07 20:44
Alrighty,  thanks for looking!

**Closed as completed by DarkholmeTenk** 2015-06-07 20:43 UTC
