### ISSUE TITLE
[BUG] cant change biome in tardis

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#444] opened 2016-02-17 08:17 UTC
something funky is happening with the tardis when you attempt to change the biome (with silver woods for example). the debug menu registers that the biome has changed but the grass stays the same, even after reloading the game. additionally, biome specific things (like planting mana beans) cannot be performed

**Comment by FoxPotato** [comment] 2016-02-17 09:33
I'd have to check the vanilla world provider but this could be because the TardisWorldProvider always returns BiomeGenBase.Plains

**Comment by AlienXtream** [comment] 2016-02-17 12:11
any specific reason why? and could the tardis have its own biome classified as "magic" (KINDA makes sense right...)? that removes the NEED to change it with thaumcraft. still wouldn't fix the issue which (i assume) would probably be a conflict between 2 values, one overriding the other right? to clarify, i basicly wanted to have mana beans and snow golems in the tardis (the latter obviously leaving snow) for automation reasons :P thats how i stumbled across this in short :)

**Comment by DarkholmeTenk** [comment] 2016-02-17 12:12
Well technically it's not got the bio part, so shouldn't have a biome

**Comment by AlienXtream** [comment] 2016-02-17 12:13
hey?

**Comment by FoxPotato** [comment] 2016-02-17 12:14
No dark, you did override the getBiome. Which is fucking it up I think.

**Comment by AlienXtream** [comment] 2016-02-17 12:15
lol, you can tell dark has forgotten some things he's done :P

**Comment by FoxPotato** [comment] 2016-02-17 12:20
What mod do you use to change biome? If the problem is where I think it is it would be easier to fix than if it really was because of the WorldProvider.

**Comment by AlienXtream** [comment] 2016-02-17 12:22
silver wood sapling from thaumcraft

**Comment by FoxPotato** [comment] 2016-02-17 14:50
Thaumcraft does not actually allow the creation of magic biomes it seems, or i'm missing something. But I think thaumcraft just doesn't allow it. I could still have a look at making the console be able to change biome.
And if that doesn't work. Well, magic doesn't really work that well with science now does it :P

**Comment by AlienXtream** [comment] 2016-02-17 20:26
Thaumcraft silver woods, if they have an aura node in them, slowly convert the area around them to magical forest. And as for your second point, "any significantly advanced technology is indistingushable from magic"

**Comment by FoxPotato** [comment] 2016-02-17 20:41
1, I got it to work. After dark pointed out a mistake I made. Just making everything look good now :P 
2, advanced technology might be indistingushable from magic. But I'm pretty sure there's still a difference between Magic and Technology ;P

**Comment by AlienXtream** [comment] 2016-02-17 20:44
i suppose at this point we are not getting more philosophical about things and as such how about we just leave it as a matter of personal opinion :)

**Comment by FoxPotato** [comment] 2016-02-18 12:06
Should be fixed once the branch gets merged into the master. :+1:

**Closed as completed** 2016-02-22 15:31 UTC
