### ISSUE TITLE
Changed MC Name

### ISSUE THREAD

**Issue by Peter-Bohus** [DarkholmeTenk/TardisModIssues#541] opened 2016-06-25 22:30 UTC
Hello, I have changed my MC name on minecraft. And now I cannot enter the tardis or nothing because the tardis owner is my old minecraft name not the new one... How can the owner change this? How does he change the name to my new MC name... Thank You

**Comment by AlienXtream** [comment] 2016-06-27 16:43
see #529

**Comment by Peter-Bohus** [comment] 2016-06-27 19:52
I have done it already but thanks anyway just done it like 5 hours ago... The owner tried to do it for me but it didn't work so he bopped me and I did the command and it worked... Thanks anyway :)

**Comment by AlienXtream** [comment] 2016-06-27 20:15
My point was this is a duplicate post. Look in the closed section as well before posting. Close this "issue" please

**Comment by DarkholmeTenk** [comment] 2016-06-28 02:20
Duplicate of #529

**Closed as completed by DarkholmeTenk** 2016-06-28 02:20 UTC
