### ISSUE TITLE
[issue] Door open refusal

### ISSUE THREAD

**Issue by theNEOkun** [DarkholmeTenk/TardisModIssues#412] opened 2016-01-19 09:07 UTC
After setting coordinates and going there, the TARDIS refuses to open, and only says "[TARDIS] The door refuses to open for some reason, and I cannot use the External Scanner when this happens.

Edit: Now it refuses to open at all.

**Comment by DarkholmeTenk** [comment] 2016-01-19 09:16
Take off and land again, chances are you landed in a new chunk and something post world-gen (e.g. ae2 meteors, villages, etc) destroyed the exterior.

**Comment by theNEOkun** [comment] 2016-01-19 09:27
The problem is that it isn't with new chunks, this is me going between two old chunks going only by coordinates. The first one is saved and previously confirmed clear in a cave. The second one is ontop of a mountain, and even with landing on ground online, and me going high up, it still refuses me.

**Comment by DarkholmeTenk** [comment] 2016-01-19 09:28
can you use /ttp and exit your tardis to make sure it's actually landed? Door refuses to open for some reason typically means no exterior exists.

**Comment by theNEOkun** [comment] 2016-01-19 09:30
Yes, and the TARDIS is in a clearly open area.

**Comment by DarkholmeTenk** [comment] 2016-01-19 09:31
Kk. Pastebin your console from the time when you landed. Can you reenter your tardis from the exterior? Once you do can you exit again or is it still broken?

**Comment by theNEOkun** [comment] 2016-01-19 09:35
Sorry for being stupid, Pastebin my console how? And yes, I can both reenter and exit it. Yet when using the TARDIS flight to the exakt same coordinates, it goes back to how it was.

**Comment by DarkholmeTenk** [comment] 2016-01-19 09:35
Take the output from your console (i.e. multimc console output or whatever) and copy/paste it to pastebin.com

**Comment by theNEOkun** [comment] 2016-01-19 09:48
You mean this? :http://pastebin.com/jSs5BheR

**Comment by DarkholmeTenk** [comment] 2016-01-19 09:50
Yeah that, but can you do it from before you land to after you land, there should be some data printed about the landing. If not /tevent should print some data iirc.

**Comment by theNEOkun** [comment] 2016-01-19 10:00
http://pastebin.com/FgmY4ZPN

**Comment by DarkholmeTenk** [comment] 2016-01-19 10:03
This makes no sense. Could you try it in a new creative world? If it still persists, could you try it with just darkcore and tardismod?

**Comment by theNEOkun** [comment] 2016-01-19 10:13
It worked on two different new creative worlds. And now that I think about (though it could very well be unrelated) I had a bug where the sonic from your mod became an unstable ingot from extra utilities (though only on this world) until next time I restarted.

**Comment by DarkholmeTenk** [comment] 2016-01-19 10:26
Very very weird, could you try it with the latest darkcore from the jenkins?

**Comment by theNEOkun** [comment] 2016-01-19 10:28
The latest one is the one I am using.

**Comment by DarkholmeTenk** [comment] 2016-01-19 10:42
I'm afraid I have absolutely no idea :\

**Comment by theNEOkun** [comment] 2016-01-19 10:43
Could just be some problem with the save too. As stated before, had a bug with the sonic and unstable ingots some days ago. I'll just restart and make sure that if it happens again I'll contact you again :) Thank anyways :D

**Comment by DarkholmeTenk** [comment] 2016-01-19 10:44
Kk. Assuming some weird problem with the save. Couldn't reproduce on my end either, closing for now.

**Comment by AlienXtream** [comment] 2016-01-21 01:08
this is what was happening to me the other week dark :O

**Comment by AlienXtream** [comment] 2016-01-24 03:41
its still an issue im afraid :(

**Comment by AlienXtream** [comment] 2016-01-24 04:02
new pack, tardis mod only and this occurs 
[15:00:28] [Client thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TConTE]H:[Hit s:2 [1.6333846,-0.3646841]]
[15:00:37] [Server thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Moving to :[-25, 54, 4671] from 100,65,265
[15:00:37] [Server thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Definitely moving?
[15:00:37] [Server thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Moving to :[-25, 54, 4671] from 100,65,265
[15:00:37] [Server thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Definitely moving?
[15:00:48] [Server thread/INFO] [STDOUT]: [tardis.common.tileents.ConsoleTileEntity:getNextUnstableControl:1275]: UC:1022:true:[990, 1024, 992, 1022, 992, 1002, 996]
[15:00:48] [Client thread/INFO] [STDOUT]: [tardis.common.tileents.ConsoleTileEntity:getNextUnstableControl:1275]: UC:1022:false:[990, 1024, 992, 1022, 992, 1002, 996]
[15:00:52] [Client thread/INFO] [STDOUT]: [tardis.common.tileents.ConsoleTileEntity:readTransmittable:1427]: NewUnstable:-1 vs OldUnstable:1022 mismatch
[15:00:54] [Server thread/INFO]: AlienXtream has just earned the achievement [Taking Inventory]
[15:00:54] [Client thread/INFO]: [CHAT] AlienXtream has just earned the achievement [Taking Inventory]
[15:01:09] [Server thread/INFO] [STDOUT]: [tardis.common.command.LandingEventCommand:event:73]: TARDIS Landing : AlienXtream:2 : World 0:-25,54,4671
[15:01:32] [Server thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Changing lock
[15:01:32] [Server thread/INFO] [STDOUT]: [tardis.common.core.TardisOutput:print:50]: [TM][TCTE]Key owner = null
[15:01:32] [Client thread/INFO]: [CHAT] [TARDIS] The door refuses to open for some reason

**Comment by DarkholmeTenk** [comment] 2016-01-24 11:43
Try latest darkcore

**Closed as completed** 2016-01-24 11:57 UTC
