### ISSUE TITLE
[BUG/COMPATIBILITY] tardis controls non responsive

### ISSUE THREAD

**Issue by AlienXtream** [DarkholmeTenk/TardisModIssues#441] opened 2016-02-12 11:48 UTC
the tardis is incompatible with the following mod http://minecraft.curseforge.com/projects/dynamic-surroundings

any attempt to activate controls is futile, they all appear in default states. additionaly ALL inveractive components on the engine are missing as apparent below
![2016-02-12_17 28 19](https://cloud.githubusercontent.com/assets/12606809/13006064/64c9bd6c-d1da-11e5-86bd-143b9324753c.png)

there is no debug output in the console to reflect that the tardis console has been right-clicked nor do any messages pop up from the gauges. oddly the screen is still rotatable.

**Comment by FoxPotato** [comment] 2016-02-12 12:08
The screen is not part of the console/engine tile entity. Can you lock the door, and transmat?
If so, the problem is something with the engine and console tileentities.

**Comment by OreCruncher** [comment] 2016-02-12 13:16
Tried loading it up but I am getting an error with Darkcore.  It's trying to register a network handler and failing.  Not sure of the relationship between the network layer and manipulating devices.

**Comment by OreCruncher** [comment] 2016-02-12 13:36
See [#434] for workaround.

**Comment by DarkholmeTenk** [comment] 2016-02-12 16:32
Not my problem, imo. I use instanceof to check if the world provider is a tardis world provider. Since this is used every rendering tick, switching to string comparison would be stupid. Changing the provider on existing world registrations indiscriminately is bad practice and should be handled better by dynamic surroundings.

**Comment by OreCruncher** [comment] 2016-02-12 17:12
To be clear the change here is my shim aggregates the Tardis provider - it does not replace it.  And there are other ways than a string compare to do the check - I handle similar situations with Dynamic Surroundings.  But as mentioned in the issue thread for your project I can make some changes to avoid hooking the dimension.

**Comment by AlienXtream** [comment] 2016-02-12 17:44
that would be cool as your sound mod really adds another level of immersion to the tardis (and MC in genreral :P)

**Comment by DarkholmeTenk** [comment] 2016-02-12 17:45
What would you suggest instead of a string comparison or instanceof?

**Comment by OreCruncher** [comment] 2016-02-12 17:45
Yes.  The Tardis mod is pretty cool.  With Dynamic Surroundings and SoundFilters there is an interesting sound dynamic that is introduced.

**Comment by OreCruncher** [comment] 2016-02-12 17:56
@DarkholmeTenk In general for Dynamic Surroundings I have a client side tick handler that executes first and caches state about the player and the current world.  The remainder of my client tick handlers use that info to calculate and cache data that would be used during the render operations for that given tick.  For example in my fog handling I have to determine the various fog densities, coloration, etc.  I do this once in the client tick handling process, and refer to those pre-calculated values during a render operation.  This works for me because a tick is 1/20th of a second and extreme accuracy during a render pass isn't really required.

In your case it would be possible to do the "is this a tardis world" using some sort of dimension lookup and cache a true/false flag, and refer to that flag during the render pass.  I do not know what else you do for rendering, but any data that gets generated and can be reused between render passes for a given tick could be cached as well.

All this being said I don't mind adjusting my mod to accommodate.  I am trying to do things a bit sneaky and I do expect to trip over these things.  I am not expecting you change what you do because of how Dynamic Surroundings works.  Ultimately when it comes down to brass tacks we want the same thing: make our common player base happy. :)

**Comment by FoxPotato** [comment] 2016-02-12 18:12
I think it would be less work to just check if the dimension is a TARDIS dimension in the Dynamic surroundings mod.
And if you were to make custom sounds happen if it were a TARDIS dimension you would technically have the first tardismod addon :P

**Comment by OreCruncher** [comment] 2016-02-12 18:24
Oh, I plan on doing that.  I have code checked in already to better handle the situation.

As for this particular mod I could attach sounds to mod specific blocks.  I haven't looked at the sound list for the TardisMod, but if there are sounds in there it would be easy to do.

**Comment by AlienXtream** [comment] 2016-02-12 20:27
There's ambient sounds for the console but none (to my knowledge) for general ambiance. Though tbh...they arnt TO hard to find. Is the BBC more lenient with "copyright" around fan made content? cos i feel like they might. Sorta digressed there didnt i.... Sorry :P

**Comment by OreCruncher** [comment] 2016-02-12 20:29
I thought about that.  But I worry because I am in the States and things are a bit different RE: copyright.  These would be on Github where anyone can access.

**Comment by FoxPotato** [comment] 2016-02-12 20:33
Isn't github hosted in the states anyway? that means all files on here have to follow the usa copyright laws. But they're probably indeed copyrighted :P

**Comment by AlienXtream** [comment] 2016-02-12 20:34
Hrm... SOUNDS like resource pack support is next on the agenda. See what i did there. ( im not sorry :P)

**Comment by FoxPotato** [comment] 2016-02-12 20:37
resource pack for which mod though? :P

**Comment by AlienXtream** [comment] 2016-02-12 20:38
Orecruncher's

**Comment by AlienXtream** [comment] 2016-02-12 20:39
Orecruncher's

**Comment by AlienXtream** [comment] 2016-02-12 20:39
Damn mobile interface...

**Comment by FoxPotato** [comment] 2016-02-12 20:40
As long as the sound files are in the resources/assets/[modname] folder resourcepacks should work.

**Comment by OreCruncher** [comment] 2016-02-12 20:41
That's part - the other part is attaching those sounds to blocks and biomes.  That would require additional Json in the resource pack, and of course Dynamic Surroundings needs to be modified to load it up at the appropriate time.

(This has been on my list, just not publicized.)

**Comment by FoxPotato** [comment] 2016-02-28 12:40
Iirc this was fixed. If not, just say so and it'll reopen :P

**Closed as completed by FoxPotato** 2016-02-28 12:40 UTC

**Comment by OreCruncher** [comment] 2016-02-28 14:01
Yep, was fixed on my side.

**Comment by AlienXtream** [comment] 2016-02-28 15:08
Oops. Forgot about closing the issue XD sorry
