### ISSUE TITLE
RANDOM CIRCUT

### ISSUE THREAD

**Issue by zach2639** [DarkholmeTenk/TardisModIssues#182] opened 2015-06-01 03:06 UTC
In S4E4 of the new dr who they mentioned a "random circut " of some sort that takes you...some were random... plz add it :D

**Comment by Soyaro666** [comment] 2015-06-01 05:05
may I suggest you to read post #25 
beside that, I'm awaiting the implementation of this too

**Comment by FoxPotato** [comment] 2015-06-01 11:07
It is confirmed that he is going to add a way to have random coords.

**Comment by DarkholmeTenk** [comment] 2015-06-01 11:34
Duplicate of #25

**Closed as completed by DarkholmeTenk** 2015-06-01 11:34 UTC
Labels: duplicate

**Comment by zach2639** [comment] 2015-06-01 12:35
oh...LOL

**Comment by zach2639** [comment] 2015-06-01 12:36
sry about duplicate...i just rewached that episode...

**Comment by DarkholmeTenk** [comment] 2015-06-01 12:39
It's cool. All the code's been in place for a while; I just need to make a
model for the zigzag plotter
