### ISSUE TITLE
[BUG] screwdriver mode can't be changed when in Tardis

### ISSUE THREAD

**Issue by Soyaro666** [DarkholmeTenk/TardisModIssues#218] opened 2015-07-20 19:29 UTC
well, the title says everything. I have to leave the Tardis if I want to change the mode the screwdriver is in.

**Comment by DarkholmeTenk** [comment] 2015-07-20 19:30
Can you verify this isn't a mod conflict? Happens with just darkcore and tardismod?

**Comment by Soyaro666** [comment] 2015-07-20 19:34
it could be a conflict with extra utilities - it happened after I used an item from that mod in Tardis - but I didn't try to change mode between updating your mods and using that item. Right now I can't test it further. I'll do after returning my girlfriend to overworld ;-)

**Comment by Soyaro666** [comment] 2015-07-20 23:54
confirmed to be an incompatibility with extra utilities 1.2.8. without that mod everything works well...

Edit: Forget that line above. Without Extra Utilities it happened again. The problem seems to appear after harvesting crops in the Tardis, maybe I have to have an item in hand to let it happen. not sure about this. And it only happens in one savegame. I'll try to test further. And I reopened this because the solution I thought I've found didn't actually work.

**Comment by DarkholmeTenk** [comment] 2015-07-22 14:36
You have hunger overhaul. Calling it now.

**Comment by Soyaro666** [comment] 2015-07-22 14:37
So Tardis has a known incompatibility with that? Is there a way to avoid that problem without removing one of the mods?

**Comment by DarkholmeTenk** [comment] 2015-07-22 14:38
I have no idea, it's something in hunger overhaul that breaks all right clicking.
Making this a duplicate of #195 and progwml6/HungerOverhaul#99

**Comment by Soyaro666** [comment] 2015-07-22 14:41
alright. should we close this topic then? Or keep it open as a reminder that the problem still exists?

**Closed as completed** 2015-07-22 14:49 UTC

**Comment by DarkholmeTenk** [comment] 2015-07-22 14:52
Give this version a shot. Had a read through HO's code and it looks like if you harvest a crop, it sets the "lastDidStuffTime" to be the current world time (in ticks), but the TARDIS has a fixed world time because you know.
Hunger Overhaul is making assumptions that the getWorldTime() function is always incrementing despite no guarantee of that :p So I added some random variation on it.
Changing the time in the tardis from night to day or vice versa will probably "fix" the problem too.

**Comment by Soyaro666** [comment] 2015-07-22 14:52
I've read through #195 and there seems to be a workaround. toggling time fixed it for him. I'll give it a try ;-)

**Comment by DarkholmeTenk** [comment] 2015-07-22 14:52
Confirms my suspicions, I think :)

**Comment by Soyaro666** [comment] 2015-07-22 14:54
I guess so. I'll use that workaround for now. can't update my mods now because I'm playing in multiplayer again. thanks so far ;-)

**Comment by Soyaro666** [comment] 2015-07-22 15:28
A suggestion for others who have the same problem: Turn Tardis interior time to night before harvesting. And harvesting outside (in a village for example) does solve the problem too.
