### ISSUE TITLE
intirior wont change

### ISSUE THREAD

**Issue by zach2639** [DarkholmeTenk/TardisModIssues#200] opened 2015-06-10 16:40 UTC
when i right click then shift right click an the change button then,nothing happens.plz help

**Comment by DarkholmeTenk** [comment] 2015-06-10 17:08
It should be right click, then sneak right click; pastebin your console output and link plz

**Comment by DarkholmeTenk** [comment] 2015-06-17 09:31
Cannot reproduce & no additional info after a week -> closing for now.

**Closed as completed by DarkholmeTenk** 2015-06-17 09:31 UTC
