### ISSUE TITLE
[SUGGESTION] WAILA integration for save slots on Z-coordinates panel

### ISSUE THREAD

**Issue by Nova001Sol** [DarkholmeTenk/TardisModIssues#176] opened 2015-05-29 18:53 UTC
I would like to be able to at least tell if I have something saved to a button, preferably with coordinates. And perhaps a way to apply a color to the buttons to keep them apart. Look, you can figure out the details, I'm not that picky.

**Comment by FoxPotato** [comment] 2015-05-29 19:25
There are multiple suggestions, Dark will for sure add something to check it.

**Comment by Soyaro666** [comment] 2015-05-29 19:34
a waila integration would be the easiest for him and the worst for the players... other requests: #168 and #105

**Comment by Nova001Sol** [comment] 2015-05-29 19:59
What do you mean by 'worst for the players'? I can not see how more info is a bad thing in any way.

**Comment by FoxPotato** [comment] 2015-05-29 21:03
well, I think he means that not everyone has waila. but tbh, its better than nothing and i dont get why some people dont install waila?

**Comment by Nova001Sol** [comment] 2015-05-29 21:27
They find it annoying. But even then it's not really a drawback, more like a bonus that some players can't profit from.

**Comment by Soyaro666** [comment] 2015-05-30 11:34
@FoxPotato thats exactly what I had in mind.
without Waila you have no acces to at least half the information the Tardis gives. Maybe Dark should think about any kind of message to tell players about Waila being kind of a dependency...
nevermind, having to test each button to see if there are coordinates saved is annoying. What I wanted to show with the links is: There already are 2 very similar suggestions. Maybe we should collect the suggestions in one post and close the others?

**Comment by FoxPotato** [comment] 2015-05-30 12:04
I dont think he should add a message telling people about waila, maybe a note on the forum post but nothing more.

**Comment by DarkholmeTenk** [comment] 2015-05-31 00:33
Duplicate of #168 and #105

**Closed by DarkholmeTenk** 2015-05-31 00:33 UTC
Labels: duplicate
